addSbtPlugin("com.github.gseitz"                 % "sbt-release"              % "1.0.9")
addSbtPlugin("com.jsuereth"                      % "sbt-pgp"                  % "1.1.2")
addSbtPlugin("com.typesafe.sbt"                  % "sbt-git"                  % "1.0.0")
addSbtPlugin("org.portable-scala"                % "sbt-scalajs-crossproject" % "0.5.0")
addSbtPlugin("org.scala-js"                      % "sbt-scalajs"              % "0.6.24")
addSbtPlugin("org.xerial.sbt"                    % "sbt-sonatype"             % "2.3"  )
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"         % "2.1.0")
